name: 'Hello World'
description: 'print "Hello, World"'
inputs:
  GITHUB_TOKEN:
    description: 'github token'
    required: true
    default: 'None'
  REPOSITORY:
    description: 'github repository'
    required: true
    default: 'None'
  DEFAULT_BRANCH:
    description: 'github default branch'
    required: true
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.REPOSITORY }}
    - ${{ inputs.DEFAULT_BRANCH }}
